db_web/db_web/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import view
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',view.test,name='index'),
    url(r'^spider/',include('spider.urls',namespace='spider')),
    url(r'^sp/',include('sp.urls',namespace='sp'))
]

db_web/sp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns=[
    url(r'^info/$',views.fill_info,name='fill'),
    url(r'^salary/$',views.salary_pre,name='salary'),
    url(r'^visualization/$',views.vt,name='vt'),
    url(r'^processing/$',views.processing_page,name='processing'),
    url(r'^processing1/$',views.processing1,name='processing1'),
    url(r'test/$',views.test,name='test')
]

db_web/spider/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns=[
    # url(r'^test/$',views.test,name='test'),
    url(r'^index/$',views.index,name='index'),
    url(r'^search/$',views.search,name='search'),
    url(r'^search_disp/$',views.search_disp,name='search_disp'),
    url(r'^details/(?P<website>.+)/(?P<key>.+)/$',views.details,name='details'),

]

db_web/spider/models.py
from django.db import models

# Create your models here.


class lgzp(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=50)
    mon_wa=models.CharField(max_length=20)
    education=models.CharField(max_length=20)
    work_exp=models.CharField(max_length=20)
    work_lable=models.CharField(max_length=100)
    work_desp=models.CharField(max_length=10000)
    work_area=models.CharField(max_length=20)

    def __str__(self):
        return self.name


class qtzp(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    mon_wa = models.CharField(max_length=20)
    education = models.CharField(max_length=20)
    work_exp = models.CharField(max_length=20)
    work_lable = models.CharField(max_length=100)
    work_desp = models.CharField(max_length=10000)
    work_area = models.CharField(max_length=20)
    def __str__(self):
        return self.name


class zlzp(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    mon_wa = models.CharField(max_length=20)
    education = models.CharField(max_length=20)
    work_exp = models.CharField(max_length=20)
    work_lable = models.CharField(max_length=100)
    work_desp = models.CharField(max_length=10000)
    work_area = models.CharField(max_length=20)
    leibie=models.CharField(max_length=50)
    def __str__(self):
        return self.name

db_web/spider/views.py
from django.shortcuts import render,HttpResponseRedirect
from . import models
from .tools import get_zlzp,get_lgzp,get_qtzp,zl_info,lg_info,qt_info,page



def index(request):
    return render(request,'search.html')

def search_disp(request):
    if request.method!='POST':
        return HttpResponseRedirect('/spider/index')
    else:
        keyword=request.POST.get('keyword')
        website=request.POST.get('website')
        return HttpResponseRedirect('/spider/search/?kw={a}&ws={b}&sl=-1&sh=-1'.format(a=keyword,b=website))


def search(request):
    keyword=request.GET.get('kw')
    website=request.GET.get('ws')
    page_cot=request.GET.get('pn')
    city=request.GET.get('city')
    salaryl=request.GET.get('sl')
    salaryh=request.GET.get('sh')
    city_lst=['北京', '上海', '深圳', '武汉', '西安', '杭州', '南京', '成都', '重庆', '大连', '沈阳', '苏州', '长沙', '合肥', '宁波', '郑州', '天津', '青岛', '济南', '哈尔滨', '长春', '福州']
    if city == None:
        city = '全国'
    if page_cot == None:
        page_cot = 1
    page_lst=page(page_cot)
    if page_cot==1:
        previous=None
    else:
        previous=int(page_cot)-1
    next=int(page_cot)+1
    if website=='zlzp':
        # zlzp=1
        if salaryl=='-1' or salaryh=='-1':
            result=get_zlzp(keyword=keyword,cot=page_cot,city=city)
        else:
            result=get_zlzp(keyword=keyword,cot=page_cot,salaryl=salaryl,salaryh=salaryh,city=city)
        return render(request,'result.html',{'result':result,'keyword':keyword,'city':city,'page_cot':page_cot,'sl':salaryl,'sh':salaryh,'ws':website,'city_lst':city_lst,'page_lst':page_lst
                                             ,'previous':previous,'next':next})

    if website=='lgzp':
        if salaryl=='-1' or salaryh=='-1':
            result=get_lgzp(keyword=keyword,cot=page_cot,city=city)
        else:
            result=get_lgzp(keyword=keyword,cot=page_cot,salaryl=salaryl,salaryh=salaryh,city=city)
        return render(request,'result.html',{'result':result,'keyword':keyword,'city':city,'page_cot':page_cot,'sl':salaryl,'sh':salaryh,'ws':website,'city_lst':city_lst,'page_lst':page_lst
                                            , 'previous': previous, 'next': next})
    if website=='qtzp':
        if salaryl=='-1' or salaryh=='-1':
            result=get_qtzp(keyword=keyword,cot=page_cot,city=city)
        else:
            result=get_qtzp(keyword=keyword,cot=page_cot,salaryl=salaryl,salaryh=salaryh,city=city)
        return render(request,'result.html',{'result':result,'keyword':keyword,'city':city,'page_cot':page_cot,'sl':salaryl,'sh':salaryh,'ws':website,'city_lst':city_lst,'page_lst':page_lst
            , 'previous': previous, 'next': next})


def details(request,website,key):
    print(website)
    print('\n')
    print(key)
    referer=request.META['HTTP_REFERER']
    print(referer)
    key=key.replace('|','/')
    if website=='zlzp':
        result=zl_info(url=key)
        print('开始返回结果')
        return render(request,'jobs_single.html',{'result':result,'referer':referer})
    if website=='qtzp':
        result=qt_info(url=key)
        print('开始返回结果')
        return render(request, 'jobs_single.html', {'result': result,'referer':referer})
    if website=='lgzp':
        result=lg_info(url=key)
        print('开始返回结果')
        return render(request, 'jobs_single.html', {'result': result,'referer':referer})

# def test(request):
#     return render(request,'visualization1.html')

db_web/spider/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首页</title>
<link href="{% static 'css/select2.css' %}" rel="stylesheet"/>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-1.7.1.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/search/area.js' %}"></script>
<script type="text/javascript" src="{% static 'js/search/location.js' %}"></script>
<script type="text/javascript" src="{% static 'js/search/select2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/search/select2_locale_zh-CN.js' %}"></script>

<script type="text/javascript" src="{% static 'js/jquery.touchSlider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/js.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ks-switch.pack.js' %}"></script>


</head>

{% block body %}
{% endblock body %}
</html>

db_web/spider/templates/jobs_single.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>Jobs_single</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Seeking Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap-3.1.1.min.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!----font-Awesome----->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<!----font-Awesome----->
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
	        </button>
	    </div>
	    <!--/.navbar-header-->
	    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" style="height: 1px;">
	        <ul class="nav navbar-nav">
		        <li><a href="{{ referer }}">返回上一页</a></li>
		        <li><a href="{% url 'spider:index' %}">返回首页</a></li>
	        </ul>
	    </div>
	    <div class="clearfix"> </div>
	  </div>
	    <!--/.navbar-collapse-->
	</nav>
<div class="container">
    <div class="single">  
	   <div class="col-md-9 single_right">
		   <p>{{ result.desp }}</p>
		   <p>工作经验: {{ result.exp }}</p>
	       <p>学历要求: {{ result.edu }}</p>
		   <p>工作城市: {{ result.city }}</p>
		   <p>工资: {{ result.salary }}</p>
       </div>
       <div class="clearfix"> </div>
    </div>
</div>
</body>
</html>	

db_web/spider/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        .dw_wp{position:relative;width:1002px;margin:0 auto 10px}

        div.search {margin:0 auto;height:170px;width:627px;position: relative;top:50px}
        select.website {height: 35px;width: 80px;}
        input.content {height: 29px;width: 400px;margin-left: -6px;}
        input.search {height: 35px;width: 100px;margin-left: -7px;}

        body,div,ul{font-family:PingFang SC,Microsoft YaHei,Lantinghei SC,Helvetica Neue,Helvetica,Arial,\\5FAE\8F6F\96C5\9ED1,STHeitiSC-Light,simsun,\\5B8B\4F53,WenQuanYi Zen Hei,WenQuanYi Micro Hei,"sans-serif";margin:0;padding:0;border:0}
        a{cursor:pointer;color:#151515}a,a:hover,a:link,a:visited{text-decoration:none}a:hover,a:hoveri{color:#3697fc}
        a,input,input:focus{outline:none}
        li,ul{list-style:none}:link img,:visited img,a img{border:0;outline:none}

        #search{width:1000px;background:#fff;margin:0 auto;margin-bottom:10px;padding:10px 30px 0 15px;box-sizing:border-box;border:1px solid #eee}
        #search .div_border{width:100%;padding:20px 0;border-bottom:1px solid #eee}
        #search .div_border .itemName{float:left;font-weight:700;width:42px;line-height:28px;box-sizing:border-box;font-family:PingFangSC-Medium,Microsoft YaHei;font-size:14px;color:#333}
        #search .div_border .itemContent{margin-left:10px;box-sizing:border-box;padding-left:16px;line-height:17px;font-family:PingFangSC-Regular,Microsoft YaHei;font-size:12px;color:#666;letter-spacing:0}
        #search .div_border:last-child{border-bottom:none}

        #queryCityBox{width:100%}
        #queryCityBox #queryTitleUls li{float:left;margin-right:10px}

        .clearfix:after{content:"";display:block;height:0;clear:both;visibility:hidden}
        .clearfix{zoom:1;display:block}

        .cityChild{width:100%;background:#fff;box-sizing:border-box;position: relative;left:10px;top:-5px}
        .cityChild .choiseCity{width:100%;margin-top:4px;padding:4px 10px;box-sizing:border-box;background:#f7f7f7}
        .cityChild .choiseCity .cityItemBox{float:left;width:50px;height:20px;line-height:20px;margin:5px 10px;margin-left:0}
        .cityChild .choiseCity .other_cityLi i{position:absolute;right:12px;top:6px;display:inline-block;width:8px;height:8px;cursor:pointer;background:url("//img03.zhaopin.cn/job-site/img/job-site-sprite.png") -290px -80px}
        .cityChild .choiseCity .other_cityLi .search-list li{cursor:pointer;height:30px;line-height:30px;padding-left:10px;background:#fff;border-bottom:1px solid #e6e8ec}
        .cityChild .choiseCity .other_cityLi .search-list li a{color:#666;font-size:12px}
        .cityChild .choiseCity .other_cityLi .search-list li:hover{background:#f7f7f7}

        .zp-query{display:inline-block;font-family:PingFangSC-Regular,Microsoft YaHei;font-size:12px;color:#666;letter-spacing:0;padding:0 4px;box-sizing:border-box;border-radius:2px;background:transparent;cursor:pointer;line-height:25px}
        .zp-query:hover{color:#1787fb}
        .zp-queryChecked{display:inline-block;font-family:PingFangSC-Regular,Microsoft YaHei;font-size:12px;letter-spacing:0;padding:0 4px;line-height:25px;box-sizing:border-box;border-radius:2px;background:#1787fb;color:#fff;cursor:pointer}
        .zp-queryChecked:hover{color:#fff}

        .query_salary_box{overflow:hidden}
        .query_salary_box .salary_all{float:left;line-height:25px;padding:0 4px;font-family:PingFangSC-RegularMicrosoft YaHei;background:#1787fb;border-radius:2px;font-size:12px;color:#fff;letter-spacing:.61px;margin-right:10px;margin-top:2px;cursor:pointer}
        .query_salary_box .salaryUls{box-sizing:border-box;overflow:hidden}
        .query_salary_box .salaryUls .salaryLi{float:left;margin-right:10px;box-sizing:border-box;line-height:30px;}

        .dw_table{position:relative;top: 20px;color:#999;background-color:#FFF}
        .dw_table .el{height:40px;line-height:40px;font-size:14px;overflow:hidden;padding:0 5px;border-bottom:1px dotted #e8e8e8}
        .dw_table .el:hover{background-color:#F7F7F7}
        .dw_table .title{height:30px;line-height:30px;text-align:center;border-bottom:1px solid #e8e8e8}
        .dw_table .title:hover{background-color:#fff}
        .dw_table .title span{height:30px;line-height:30px;font-size:12px;color:#999}
        .dw_table .t1,.dw_table .t2,.dw_table .t3,.dw_table .t4{float:left;height:40px;line-height:40px;font-size:14px;overflow:hidden;padding:0 10px}
        .dw_table .t1{position:relative;width:315px;color:#FF6000}
        .dw_table .t1 span{float:left;max-width:285px}
        .dw_table .t1 span a{float:left;max-width:285px;font-size:16px;color:#333;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}
        .dw_table .t1 a:visited{color:#999}
        .dw_table .t1 a:active,.dw_table .t1 a:hover{color:#ff6000}
        .dw_table .t2{width:255px;color:#666;text-align:center}
        .dw_table .t3{width:100px;text-align:center}
        .dw_table .t4{width:130px;font-size:16px;color:#FF6000;text-align:center}

        .dw_line{position:relative;height:1px;top:-1px;background-color:#e8e8e8}

        .dw_page{position:relative;height:30px;line-height:30px;font-size:12px;color:#666;overflow:hidden;padding:15px 0 30px}
        .dw_page .p_box{position:absolute;width:200%;left:-50%}
        .dw_page .p_wp{position:absolute;margin-left:50%}
        .dw_page .p_in{position:relative;float:left;left:-50%}
        .dw_page ul{float:left;font-size:14px}
        .dw_page ul{height:30px}
        .dw_page li{float:left;width:30px;height:30px;line-height:30px;text-align:center;margin-right:10px;background-color:#FFF}
        .dw_page li a{display:block;width:30px;font-size:12px;color:#666;border:1px solid #e8e8e8}
        .dw_page li a:hover{color:#FF6000;border-color:#FF6000}
        .dw_page li.bk,.dw_page li.bk a{width:64px}
        .dw_page li.bk span{display:block;color:#BBB;font-size:12px;border:1px solid #e8e8e8}

        .footer{clear:both;width:100%;height: 100px}

    </style>

</head>

<body>
    <div class="dw_wp">
        <div class="search">
            <form action="{% url 'spider:search_disp' %}"  method="post">
                {% csrf_token %}
                <select class="website" name="website" id="website">
                <option value="zlzp" selected>智联招聘</option>
                <option value="qtzp">前途无忧</option>
                <option value="lgzp">拉钩网</option>
                </select>
                <input class="content" name="keyword" placeholder="{{keyword}}" autocomplete="off"/>
                <input class="search" type="submit" value="搜索" />
            </form>
        </div>

        <div id="search">
            <div class="div_border">
                <div class="itemName">地点:</div>
                <div class="itemContent ">
                    <div id="queryCityBox">
                        <div class="cityChild">
                            <ul class="choiseCity clearfix" id="citybox">
                                <li class="cityItemBox"><a class="zp-query zp-queryChecked" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl={{ sl }}&sh={{ sh }}&city=全国">全国</a></li>
                                {% for i in city_lst %}
                                <li class="cityItemBox"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl={{ sl }}&sh={{ sh }}&city={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div style="clear:both"></div>
            </div>

            <div class="div_border">
                <div class="itemName">月薪:</div>
                <div class="itemContent">
                    <div class="query_salary_box">

                        <ul class="salaryUls" id="salarybox">
                            <li class="cityItemBox"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=-1&sh=-1&city={{ city }}">不限</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=1001&sh=2000&city={{ city }}">1K-2K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=2001&sh=4000&city={{ city }}">2K-4K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=4001&sh=6000&city={{ city }}">4K-6K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=6001&sh=8000&city={{ city }}">6K-8K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=8001&sh=10000&city={{ city }}">8K-10K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=10001&sh=15000&city={{ city }}">10K-15K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=15001&sh=25000&city={{ city }}">15K-25K</a></li>
                            <li class="salaryLi"><a class="zp-query" href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl=25001&sh=35000&city={{ city }}">25K-35K</a></li>
                        </ul>
                    </div>
                </div>
                <div style="clear:both"></div>
            </div>
        </div>

        <div class="dw_table">
            <div class="el title">
                <span class="t1">职位名</span>
                <span class="t2">工作经验</span>
                <span class="t3">工作地点</span>
                <span class="t4">薪资</span>
            </div>
            {% for i in result %}
            <div class="el">
                <p3 class="t1"><span><a title="{{ i.name }}" onmousedown="" href="{% url 'spider:details' ws i.url %}">{{ i.name }}</a></span></p3>
                <span class="t2">{{ i.exp }}</span>
                <span class="t3">{{ i.city }}</span>
                <span class="t4">{{ i.salary }}</span>
            </div>
            {% endfor %}

            <div class="dw_line"></div>

            <div class="dw_page">
                <div class="p_box">
                    <div class="p_wp">
                        <div class="p_in">
                            <ul>
                                {% if previous %}
                                <li class="bk"><a href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl={{ sl }}&sh={{ sh }}&city={{ city }}&pn={{ previous }}">上一页</a></li>
                                {% endif %}
                                {% for i in page_lst %}
                                <li><a href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl={{ sl }}&sh={{ sh }}&city={{ city }}&pn={{i}}">{{ i }}</a></li>
                                {% endfor %}
                                <li class="bk"><a href="/spider/search/?kw={{ keyword }}&ws={{ ws }}&sl={{ sl }}&sh={{ sh }}&city={{ city }}&pn={{ next }}">下一页</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer"></div>
    </div>
    <script>
        var webst="{{ ws|safe }}";
        if (webst==='zlzp'){
            document.getElementById('website').value='zlzp'
        }else if (webst==='lgzp'){
            document.getElementById('website').value='lgzp'
        }else {
            document.getElementById('website').value='qtzp'
        }

        var city="{{ city|safe }}";
        var citybox=document.getElementById('citybox').children;
        for (i=0;i<citybox.length;i++){
            if (citybox[i].textContent===city){
                citybox[i].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else{
                citybox[i].children[0].setAttribute('class','zp-query')
                 }
            }

        var salary="{{ sl|safe }}";
        var salarybox=document.getElementById('salarybox').children;
        if (salary==='-1'){
            salarybox[0].children[0].setAttribute('class','zp-query zp-queryChecked')
        }else{
            salarybox[0].children[0].setAttribute('class','zp-query')
            if (salary==='1001'){
                salarybox[1].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='2001'){
                salarybox[2].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='4001'){
                salarybox[3].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='6001'){
                salarybox[4].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='8001'){
                salarybox[5].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='10001'){
                salarybox[6].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='15001'){
                salarybox[7].children[0].setAttribute('class','zp-query zp-queryChecked')
            }else if (salary==='25001'){
                salarybox[8].children[0].setAttribute('class','zp-query zp-queryChecked')
            }
        }


    </script>

</body>
</html>

db_web/spider/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style type="text/css">
        div.search
        {
            margin:0 auto;
            height:36px;
            width:627px;
            position: relative;
            top:90px;
        }
        select.website
        {
            height: 37px;
            width: 125px;
        }
        input.content
        {
            height: 31px;
            width: 400px;
            margin-left: -6px;
        }
        input.search
        {
            height: 37px;
            width: 100px;
            margin-left: -7px;
        }
    </style>
</head>
<body>
    <div class="search">
        <form action="{% url 'spider:search_disp' %}"  method="post">
            {% csrf_token %}
            <select class="website" name="website">
                <option value="zlzp" selected>智联招聘</option>
                <option value="qtzp">前途无忧</option>
                <option value="lgzp">拉钩网</option>
            </select>
            <input class="content" name="keyword" placeholder="  请输入搜索内容" autocomplete="off"/>
            <input class="search" type="submit" value="搜索" />
        </form>
    </div>
</body>
</html>