db_web/db_web/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import view
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',view.test,name='index'),
    url(r'^spider/',include('spider.urls',namespace='spider')),
    url(r'^sp/',include('sp.urls',namespace='sp'))
]

db_web/sp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns=[
    url(r'^info/$',views.fill_info,name='fill'),
    url(r'^salary/$',views.salary_pre,name='salary'),
    url(r'^visualization/$',views.vt,name='vt'),
    url(r'^processing/$',views.processing_page,name='processing'),
    url(r'^processing1/$',views.processing1,name='processing1'),
    url(r'test/$',views.test,name='test')
]

db_web/sp/models.py
from django.db import models

# Create your models here.
class BDT(models.Model):        #对大数据需求最剧烈的行业排名
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=100)
    count=models.IntegerField()

    def __str__(self):
        return self.name

class ITC(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=100)
    count=models.IntegerField()

    def __str__(self):
        return self.name

class ITS(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=100)
    salary=models.FloatField()

    def __str__(self):
        return self.name

class BDC(models.Model):        #对大数据需求最多的10个城市
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=100)
    salary=models.FloatField(null=True)
    count=models.IntegerField()

    def __str__(self):
        return self.name

class CSR(models.Model):        #工资最高的10个城市
    id=models.IntegerField(primary_key=True)
    city=models.CharField(max_length=100)
    salary=models.FloatField()

    def __str__(self):
        return self.city

class BPS(models.Model):        #大数据职位需求量排名以及工资
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=100)
    salary=models.FloatField()
    count=models.IntegerField()

    def __str__(self):
        return self.name

db_web/sp/views.py
from django.shortcuts import render,HttpResponseRedirect
from . import models
import json
import pyspark
from pyspark.sql import HiveContext
from pyspark.sql import SparkSession
from pyspark import SparkContext
from .tools import lable_filter,mon_wa_trans,text_division,desp_text_division,work_exp_trans,new_edu_trans,city_trans,lable_trans,features_trans
from .tools import result_trans
from pyspark.ml.feature import IDFModel,HashingTF
from pyspark.mllib.classification import NaiveBayesModel
from pyspark.sql.types import Row,StructType,StructField,StringType,IntegerType
from pyspark.mllib.linalg import DenseVector
# Create your views here.
def fill_info(request):
    lst_pos=['web','系统工程师','高级软件工程师','软件工程师','手机应用','计算机','硬件','数据挖掘','数据库工程师','单片机','嵌入式硬件','嵌入式软件','ios','安卓','android','硬件工程师','系统测试','运维','前端',
             'java开发','高级硬件工程','区块链','大数据','深度学习','人工智能','机器视觉','算法','ui',
              '游戏开发','网络管理','网页设计/制作/美工','软件测试','通信','电子技术','机器人','电气工程师','自动化','电路工程',
              'cocos2d-x','物联网','系统架构','erp实施','电子工程','系统集成','集成电路','硬件测试','数据分析','射频工程','网络安全',
              '半导体','flash']
    lst_exp=['10年以上','5-10年','3-5年','1-3年','无经验']

    return render(request,'fill.html',{'position':lst_pos,'exp':lst_exp})
def salary_pre(request):
    sc=SparkContext('local','test')
    spark = SparkSession.builder.getOrCreate()
    hive_con=HiveContext(sc)
    nd_idf=IDFModel.load('hdfs://localhost:9000/ndidf')
    agg_idf=IDFModel.load('hdfs://localhost:9000/aggidf')
    model=NaiveBayesModel.load(sc,'hdfs://localhost:9000/nymodel')
    # hive_con.sql('use zp')
    # testdata=hive_con.sql('select education,mon_wa,name,work_area,work_desp,work_exp,work_lable from `qtzp` where id=789')
    # testdataRDD = testdata.rdd.map(lambda i: Row(**{
    #     'education': new_edu_trans(i.education),
    #     'salary': mon_wa_trans(i.mon_wa),
    #     'name': i.name,
    #     'city': i.work_area,
    #     'work_desp': i.work_desp,
    #     'work_exp': i.work_exp,
    #     'work_lable': i.work_lable
    # }))
    # dataDF=testdataRDD.map(lambda i:Row(**{
    #     'salary': int(i.salary),
    #     'agg': [i.education] + [i.city] + [i.work_lable] + [i.work_exp],
    #     'name_and_desp': desp_text_division(i.name + ',' + i.work_desp)
    # })).toDF()
    # dataDF.show()
    city=request.POST.get('city')
    edu=request.POST.get('education')
    introduce=request.POST.get('introduce')
    position=request.POST.get('job')
    exp=request.POST.get('exp')
    dataRDD=sc.parallelize([[edu,city,position,exp,introduce]])
    # schema=StructType([StructField('education',StringType(),True),StructField('work_area',StringType(),True),StructField('work_lable',
    #         StringType(),True),StructField('work_exp',StringType(),True),StructField('work_desp',StringType(),True)])
    # rowRDD=dataRDD.map(lambda i:Row(i[0],i[1],i[2],i[3],i[4]))
    # dataDF=spark.createDataFrame(rowRDD,schema)
    # dataDF.show()
    dataDF=dataRDD.map(lambda i:Row(**{
        'education':i[0],
        'work_area':i[1],
        'work_lable':i[2],
        'work_exp':i[3],
        'work_desp':i[4]
    })).map(lambda i:Row(**{
        'education':str(new_edu_trans(i.education)),
        'city':[i.work_area],
        'work_desp':i.work_desp,
        'work_lable':[i.work_lable],
        'work_exp':[i.work_exp]
    })).map(lambda i:Row(**{
        'agg':[i.education] + i.city + i.work_lable + i.work_exp,
        'name_and_desp':desp_text_division(i.work_desp)
    })).toDF()
    dataDF.show()

    ndtf = HashingTF(inputCol='name_and_desp', outputCol='ndFeatures', numFeatures=10240)
    aggtf = HashingTF(inputCol='agg', outputCol='Features_agg', numFeatures=256)
    data = ndtf.transform(dataDF)
    data = aggtf.transform(data)
    idfdata = nd_idf.transform(data)
    idfdata = agg_idf.transform(idfdata)
    RDD = idfdata.rdd
    # featuresRDD = RDD.map(lambda i: (i.salary, i.ndfeatures.toArray().tolist() + i.features_agg.toArray().tolist()))  #test
    featuresRDD = RDD.map(lambda i: i.ndfeatures.toArray().tolist() + i.features_agg.toArray().tolist())      #应用
    # featuresRDD = featuresRDD.map(lambda i: features_trans(i))      #test
    featuresRDD=featuresRDD.map(lambda i:DenseVector(i))       #应用
    # result=featuresRDD.map(lambda i: model.predict(i.features)).collect()       #test
    result=featuresRDD.map(lambda i:model.predict(i)).collect()
    # result=result[0]
    spark.stop()
    sc.stop()
    city_mean=models.CSR.objects.using('db2').filter(city__contains=city)
    city_mean=city_mean[0].salary
    salary=result_trans(result[0])
    pos_mean=models.ITS.objects.using('db2').get(name=position)
    pos_mean=pos_mean.salary
    data_lst=[city_mean,pos_mean,salary]
    data_lst=json.dumps(data_lst)
    return render(request,'salary.html',{'result':result,'position':position,'city':city,'edu':edu,'exp':exp,'data':data_lst})


def vt(request):
    leibie=request.GET.get('lb')
    if leibie==None:
        data=models.BDT.objects.using('db2').all()
        name_lst=[]
        lst=[]
        for i in data:
            dct={}
            dct['value']=i.count
            dct['name']=i.name
            print(dct)
            lst.append(dct)
        for i in lst:
            name_lst.append(i['name'])
        print(name_lst)
        lst=json.dumps(lst[1:])
        name_lst=json.dumps(name_lst[1:])
        return render(request,'visualization.html',{'data':lst,'name':name_lst})
    if leibie=='1':
        city_lst=[]
        sal_lst=[]
        data=models.CSR.objects.using('db2').all()
        data=data[:10]
        for i in data:
            city_lst.append(i.city)
            sal_lst.append(i.salary)
        city_lst=json.dumps(city_lst)
        sal_lst=json.dumps(sal_lst)
        print(city_lst)
        print(sal_lst)
        return render(request,'visualization1.html',{'city':city_lst,'salary':sal_lst})
    if leibie=='2':
        lst=[]
        itc_data=models.ITC.objects.using('db2').all()
        its_data=models.ITS.objects.using('db2').all()
        name_lst=[]
        for i in itc_data:      #完成职位lst
            name_lst.append(str(i))
        for i in name_lst:
            tem_lst=[]
            tem_lst.append(int(itc_data.get(name=i).count))
            tem_lst.append(int(its_data.get(name=i).salary))
            tem_lst.append(i)
            lst.append(tem_lst)
        lst=json.dumps(lst)
        print(lst)
        return render(request,'visualization2.html',{'data':lst})
    if leibie=='3':
        lst=[]
        data=models.BPS.objects.using('db2').all()
        for i in data:
            tem_lst=[]
            tem_lst.append(i.count)
            tem_lst.append(i.salary)
            tem_lst.append(i.name)
            lst.append(tem_lst)
        lst=json.dumps(lst)
        return render(request,'visualization3.html',{'data':lst})
    if leibie=='4':
        lst=[]
        data=models.BDC.objects.using('db2').filter(count__gte=10)
        for i in data:
            tem_lst=[]
            tem_lst.append(i.count)
            tem_lst.append(i.salary)
            tem_lst.append(i.name)
            lst.append(tem_lst)
        lst=json.dumps(lst)
        return render(request,'visualization4.html',{'data':lst})

def processing_page(request):
    lst_pos = ['web', '系统工程师', '高级软件工程师', '软件工程师', '软件', '软件开发', '手机应用', '计算机', '硬件', '数据挖掘', '数据库工程师', '单片机', '嵌入式硬件',
               '嵌入式软件', 'ios', '安卓', 'android', '硬件工程师', '系统测试', '运维', '前端',
               'java开发', '高级硬件工程', '区块链', '大数据', '深度学习', '人工智能', '机器视觉', '算法', 'ui',
               '游戏开发', '网络管理', '网页设计/制作/美工', '软件测试', '通信', '电子技术', '机器人', '电气工程师', '自动化', '电路工程',
               'cocos2d-x', '物联网', '系统架构', 'erp实施', '电子工程', '系统集成', '集成电路', '硬件测试', '数据分析', '射频工程', '网络安全',
               '半导体', 'flash']
    lst_exp = ['10年以上', '5-10年', '3-5年', '1-3年', '无经验']
    return render(request,'processing.html',{'position':lst_pos,'exp':lst_exp})

def processing1(request):
    if request.method!='POST':
        return HttpResponseRedirect('/sp/processing')
    else:
        progress=request.POST.get('progress')
        sc = SparkContext('local', 'test')
        spark = SparkSession.builder.getOrCreate()
        if progress=='1':
            city = request.POST.get('city')
            edu = request.POST.get('education')
            introduce = request.POST.get('introduce')
            position = request.POST.get('job')
            exp = request.POST.get('exp')
            print(city,edu,introduce,position,exp)
            explain1='第一步：将信息按照类别形成RDD后,通过map操作，将传入的信息进行合并，转化，并根据词频进行分词处理，后形成dataframe，便于下一步操作，此时信息的状态如下'
            dataRDD = sc.parallelize([[edu, city, position, exp, introduce]])
            dataDF = dataRDD.map(lambda i: Row(**{
                'education': i[0],
                'work_area': i[1],
                'work_lable': i[2],
                'work_exp': i[3],
                'work_desp': i[4]
            })).map(lambda i: Row(**{
                'education': str(new_edu_trans(i.education)),
                'city': [i.work_area],
                'work_desp': i.work_desp,
                'work_lable': [i.work_lable],
                'work_exp': [i.work_exp]
            })).map(lambda i: Row(**{
                'agg': [i.education] + i.city + i.work_lable + i.work_exp,
                'name_and_desp': desp_text_division(i.work_desp)
            })).toDF()
            dct={}
            for i in dataDF.collect():
                dct['agg1']=i[0]
                dct['nd1']=i[1]
            # spark.stop()
            # sc.stop()
            agg_pro1='将学历,城市,职位,经验合并为一行:'
            nd_pro1='将个人简介单独为一行:'
            agg_pro2='学历,经验,职位,城市形成的向量:'
            nd_pro2='个人介绍形成的向量:'
            explain2='第二步:将形成的list通过spark的机器学习包转化包通过if-idf算法形成特征向量,便于下一步机器学习的使用'
            nd_idf = IDFModel.load('hdfs://localhost:9000/nd_idf_test')
            agg_idf = IDFModel.load('hdfs://localhost:9000/agg_idf_test')
            ndtf = HashingTF(inputCol='name_and_desp', outputCol='ndFeatures', numFeatures=10240)

db_web/sp/templates/base1.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>招聘信息处理结果可视化</title>
<link href="{% static 'vt/css/style.css' %}" type='text/css' rel="stylesheet"/>
<script src="{% static 'vt/js/echarts.min.js' %}"></script>
</head>
{% block body %}
{% endblock body %}
</html>

db_web/sp/templates/fill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body{font:12px/1 "微软雅黑",Tahoma,Helvetica,Arial,"\5b8b\4f53",sans-serif}
        #resume{width:1200px;margin:0 auto;position: relative;top:100px}
        #resume .inputBox{width:600px;margin:0 auto;margin-bottom:20px}
        #resume .rs_div{position:relative;display:inline-block;*display:inline;*zoom:1;vertical-align:top;margin-right:15px;*z-index:998}
        #resume .radioBox{width:1200px;margin:0 auto;margin-bottom:20px}
        #resume .radio_div{position:relative;display:inline-block;*display:inline;vertical-align:top;margin-right:15px;left:380px;width: 700px}
        #resume .rs_input{width:280px;border:1px solid #32c5cd!important;margin:0;padding:0;height:30px;autocomplete:"off";font-family: "微软雅黑";font-size:14px;padding-left: 5px}
        #resume .rs_textarea{font-family: "微软雅黑";width:275px;height:100px;border:1px solid #32c5cd!important;margin:0;padding:0;resize: none;font-size:14px;padding:5px 5px 5px 5px}
        .rs_input:focus{border:1px solid #32c5cd!important;}
        #resume span{width:162px;text-align:right;display:inline-block;*display:inline;*zoom:1;vertical-align:top;height:32px;line-height:32px;font-size:14px;margin-right:20px;color:#333333}
        #resume label{width:110px;text-align:left;display:inline-block;*display:inline;*zoom:1;vertical-align:top;line-height:32px;font-size:14px;margin-right:20px;color:#333333}

        #sub{height:40px;width: 120px;background: deepskyblue;font-family: "微软雅黑";font-size:14px;color: #FFFFFF;border:none}
        #sub:hover{border-bottom:solid 1px #333}
        .sub{height:40px;width: 120px;margin:0 auto;margin-top: 50px}

    </style>
</head>
<body>
    <div id="resume">
        <form action="{% url 'sp:salary' %}" method="post">
            {% csrf_token %}
            <div class="inputBox">
                <span>学历：</span>
                <div class="rs_div">
                    <input class="rs_input" name="education" type="text" value="">
                </div>
            </div>

            <div class="inputBox">
                <span>城市：</span>
                <div class="rs_div">
                    <input class="rs_input" name="city" type="text">
                </div>
            </div>

            <div class="inputBox">
                <span>个人简介：</span>
                <div class="rs_div">
                    <textarea class="rs_textarea" name="introduce" type="text"></textarea>
                </div>
            </div>
            <div class="inputBox">
                <span>希望从事的工作：</span>
            </div>
            <div class="radioBox">
                <div class="radio_div">
                    {% for i in position %}
                    <label><input type="radio" name="job" value="{{i}}">{{ i }}</label>
                    {% endfor %}
                </div>
            </div>
             <div class="inputBox">
                <span>工作经验：</span>
            </div>
            <div class="radioBox">
                <div class="radio_div">
                    {% for i in exp %}
                    <label><input type="radio" name="exp" value="{{i}}">{{ i }}</label>
                    {% endfor %}
                </div>
            </div>
            <div class="sub">
                <input id="sub" type=submit name="submit1" value="提交"/>
            </div>
        </form>
    </div>
</body>
</html>

db_web/sp/templates/guide.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<!--框架必需start-->
<script type="text/javascript" src="{% static 'qu/js/jquery.js' %}">

</script>
<script type="text/javascript" src="{% static 'qu/js/language/cn.js' %}>">

</script>
<script type="text/javascript" src="{% static 'qu/js/framework.js' %}">

</script>
<link href="{% static 'qu/css/import_basic.css' %}" rel="stylesheet" type="text/css"/>

<link rel="stylesheet" type="text/css" id="skin" href="{% static 'qu/skins/blue/style.css' %}" scrollerY="false"/>
	</head>
<body>
	<div class="welcome_process" id="openContent">
		<div class="welcome_process_list">
			<ul>
				<li><a href="{% url 'spider:index' %}">爬取招聘网站</a></li>
				<li><a href="{% url 'sp:vt' %}">数据可视化</a></li>
				<li><a href="{% url 'sp:fill' %}">工资预测</a></li>
				<li><a href="{% url 'sp:processing' %}">数据处理</a></li>
			</ul>
		</div>
	</div>
</body>
</html>

db_web/sp/templates/processing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body{font:12px/1 "微软雅黑",Tahoma,Helvetica,Arial,"\5b8b\4f53",sans-serif}
        #resume{width:1200px;margin:0 auto;position: relative;top:100px}
        #resume .inputBox{width:600px;margin:0 auto;margin-bottom:20px}
        #resume .rs_div{position:relative;display:inline-block;*display:inline;*zoom:1;vertical-align:top;margin-right:15px;*z-index:998}
        #resume .radioBox{width:1200px;margin:0 auto;margin-bottom:20px}
        #resume .radio_div{position:relative;display:inline-block;*display:inline;vertical-align:top;margin-right:15px;left:380px;width: 700px}
        #resume .rs_input{width:280px;border:1px solid #32c5cd!important;margin:0;padding:0;height:30px;autocomplete:"off";font-family: "微软雅黑";font-size:14px;padding-left: 5px}
        #resume .rs_textarea{font-family: "微软雅黑";width:275px;height:100px;border:1px solid #32c5cd!important;margin:0;padding:0;resize: none;font-size:14px;padding:5px 5px 5px 5px}
        .rs_input:focus{border:1px solid #32c5cd!important;}
        #resume span{width:162px;text-align:right;display:inline-block;*display:inline;*zoom:1;vertical-align:top;height:32px;line-height:32px;font-size:14px;margin-right:20px;color:#333333}
        #resume label{width:110px;text-align:left;display:inline-block;*display:inline;*zoom:1;vertical-align:top;line-height:32px;font-size:14px;margin-right:20px;color:#333333}

        #sub{height:40px;width: 120px;background: deepskyblue;font-family: "微软雅黑";font-size:14px;color: #FFFFFF;border:none}
        #sub:hover{border-bottom:solid 1px #333}
        .sub{height:40px;width: 120px;margin:0 auto;margin-top: 50px}

    </style>
</head>
<body>
<h1 align="center">请在此输入一条招聘信息，之后点击下一步，您将可以观测一条信息是如何进行处理的</h1>
    <div id="resume">
        <form action="{% url 'sp:processing1' %}" method="post">
            {% csrf_token %}
            <div class="inputBox">
                <span>学历：</span>
                <div class="rs_div">
                    <input class="rs_input" name="education" type="text" value="">
                </div>
            </div>

            <div class="inputBox">
                <span>城市：</span>
                <div class="rs_div">
                    <input class="rs_input" name="city" type="text">
                </div>
            </div>

            <div class="inputBox">
                <span>个人简介：</span>
                <div class="rs_div">
                    <textarea class="rs_textarea" name="introduce" type="text"></textarea>
                </div>
            </div>
            <div class="inputBox">
                <span>希望从事的工作：</span>
            </div>
            <div class="radioBox">
                <div class="radio_div">
                    {% for i in position %}
                    <label><input type="radio" name="job" value="{{i}}">{{ i }}</label>
                    {% endfor %}
                </div>
            </div>
             <div class="inputBox">
                <span>工作经验：</span>
            </div>
            <div class="radioBox">
                <div class="radio_div">
                    {% for i in exp %}
                    <label><input type="radio" name="exp" value="{{i}}">{{ i }}</label>
                    {% endfor %}
                </div>
            </div>
			<input type="hidden" value="1" name="progress">
            <div class="sub">
                <input id="sub" type=submit name="submit1" value="下一步"/>
            </div>
        </form>
    </div>
</body>
</html>

db_web/sp/templates/processing1.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>Jobs_single</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Seeking Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap-3.1.1.min.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!----font-Awesome----->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<!----font-Awesome----->
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
	        </button>
	    </div>
	    <!--/.navbar-header-->
	    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" style="height: 1px;">
	        <ul class="nav navbar-nav">
		        <li><a href="{% url 'index' %}">返回导航页</a></li>
	        </ul>
	    </div>
	    <div class="clearfix"> </div>
	  </div>
	    <!--/.navbar-collapse-->
	</nav>
<div class="container">
    <div class="single">  
	   <div class="col-md-9 single_right">

		   <p>{{ explain1 }}</p>

		   <span>{{agg_pro1}}</span>
           <p>{{ data.agg1 }}</p>

           <span>{{nd_pro1}}</span>
            <p>{{ data.nd1 }}</p>

           <span>{{ explain2 }}</span>

           <span>{{agg_pro2}}</span>
           <p>{{ data.agg2 }}</p>

           <span>{{nd_pro2}}</span>
           <p>{{ data.nd2 }}</p>
	   </div>

       <div class="clearfix"> </div>

    </div>
</div>
</body>
</html>	

db_web/sp/templates/salary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body{font:12px/1 "微软雅黑",Tahoma,Helvetica,Arial,"\5b8b\4f53",sans-serif}
        #result{width:1000px;margin:0 auto}
        #result .blank{width:978px;height:103px}
        #result .show{width:978px;height:103px;border:1px solid #ccc;border-top:5px solid #32c5cd;position:fixed;top:0;z-index:3000;background:#f9fefe;magin:0 auto;padding:12px 20px 0 24px;left:50%;margin-left:-512px}
        #result .show .job{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:390px;height:32px;line-height:32px;display:inline-block;*display:inline;*zoom:1;color:#333;font-size:26px;vertical-align:top;margin-right:30px}
        #result .show .experience{width:690px;height:32px;line-height:32px;font-size:14px;color:#777;white-space:nowrap;text-overflow:ellipsis;}
        #result .show .education{width:978px;height:26px;display:inline-block;*display:inline;*zoom:1;vertical-align:bottom;padding-right:10px;font-size:18px;line-height:26px;color:#34b6bd}
        #result .sub{margin:20px auto;text-align:center;}
        #result .sub input{margin:20px auto;text-align:center;width:120px;height:40px;text-align:center;color:#fff;background:#32c5cd;font-size:16px;line-height:40px;border:none;font-family:"Microsoft Yahei"}
        #result .data{width:960px;height:660px;margin:0 auto;border:1px solid #eaeaea;}
        #result .container{margin:0 auto;padding:12px 20px 0 24px}
        #result .container .blank{height:50px}
    </style>
    <script src="{% static 'vt/js/echarts.min.js' %}"></script>
</head>
<body>
    <div id="result">
        <div class="blank"></div>
        <div class="show">
            <div>
                <span title="" class="job">工作：{{position}}</span>
                <span title="" class="job">城市：{{city}}</span>
            </div>
            <div class="experience">
                工作经验：{{exp}}
            </div>
            <div class="education">
                学历：{{edu}}
            </div>
        </div>

        <div class="container">
            <div class="blank"></div>
            <div class="data" id="main">
            </div>
            <div class="sub">
                <a href="{% url 'sp:fill' %}"><input id="" type="button" value="再测一次"/></a>
            </div>
        </div>
    </div>
</body>
<script>
    var myChart = echarts.init(document.getElementById('main'));
// 指定图表的配置项和数据

var info_lst=['您所在城市的平均工资','您所选职位的平均工资','预测所得您的工资约为'];
var sal_lst={{ data|safe }}
option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : info_lst,
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'工资',
            type:'bar',
            barWidth: '60%',
            data:sal_lst
        }
    ]
};

// 使用刚指定的配置项和数据显示图表。
myChart.setOption(option);
</script>
</html>